### ISSUE TITLE
Anything unique.

### ISSUE THREAD

**Issue by Abhiramborige** [Abhiramborige/Dynamic-Greetings#1]
Any kind of styling, animations, etc... can be added.

**Comment by JVisuri1** [comment]
Feedback on #2 is always appreciated!

**Comment by kwing25** [comment]
Added some styles including animation. PR [#3](https://github.com/Abhiramborige/Dynamic-Greetings/pull/3)

**Comment by Abhiramborige** [comment]
> Feedback on #2 is always appreciated!

@JVisuri1 Hey sorry dude, I have to revert your PR, as there was conflict arising. your idea of navbar is good but let that be as a footer itself. Sorry for that
